### ISSUE TITLE
运行命令 roslaunch airsim_ctrl ctrl_md_exploration.launch出现报错

### ISSUE THREAD

**Issue by ltf1001** [HKUST-Aerial-Robotics/APACE#1]
感谢作者分享如此杰出的工作。当我在运行此代码时，运行到roslaunch airsim_ctrl ctrl_md_exploration.launch出现了错误，错误为
WARNING: [/home/dell/APACE/src/APACE/airsim_ctrl/launch/ctrl_md_exploration.launch] unknown <arg> attribute 'type'
[airsim_node-1] process has died [pid 1829541, exit code -6, cmd /home/dell/APACE/devel/lib/airsim_ros_pkgs/airsim_node __name:=airsim_node __log:=/home/dell/.ros/log/52e60206-3246-11ef-94d3-1515a4912863/airsim_node-1.log].
log file: /home/dell/.ros/log/52e60206-3246-11ef-94d3-1515a4912863/airsim_node-1*.log两个错误。完整的报错：
... logging to /home/dell/.ros/log/52e60206-3246-11ef-94d3-1515a4912863/roslaunch-dell-System-Product-Name-1829527.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dell-System-Product-Name:33575/

SUMMARY
========

PARAMETERS
 * /airsim_ctrl/ctrl_rate: 100.0
 * /airsim_ctrl/full_thrust: 16.716
 * /airsim_ctrl/gain/hover/Ka0: 1.0
 * /airsim_ctrl/gain/hover/Ka1: 1.0
 * /airsim_ctrl/gain/hover/Ka2: 1.0
 * /airsim_ctrl/gain/hover/Kp0: 1.7
 * /airsim_ctrl/gain/hover/Kp1: 1.7
 * /airsim_ctrl/gain/hover/Kp2: 1.7
 * /airsim_ctrl/gain/hover/Krp: 25.0
 * /airsim_ctrl/gain/hover/Kv0: 1.5
 * /airsim_ctrl/gain/hover/Kv1: 1.5
 * /airsim_ctrl/gain/hover/Kv2: 1.5
 * /airsim_ctrl/gain/hover/Kvi0: 0.2
 * /airsim_ctrl/gain/hover/Kvi1: 0.2
 * /airsim_ctrl/gain/hover/Kvi2: 0.2
 * /airsim_ctrl/gain/hover/Kyaw: 5.0
 * /airsim_ctrl/gain/track/Ka0: 1.0
 * /airsim_ctrl/gain/track/Ka1: 1.0
 * /airsim_ctrl/gain/track/Ka2: 1.0
 * /airsim_ctrl/gain/track/Kp0: 1.5
 * /airsim_ctrl/gain/track/Kp1: 1.5
 * /airsim_ctrl/gain/track/Kp2: 1.5
 * /airsim_ctrl/gain/track/Krp: 30.0
 * /airsim_ctrl/gain/track/Kv0: 1.5
 * /airsim_ctrl/gain/track/Kv1: 1.5
 * /airsim_ctrl/gain/track/Kv2: 1.5
 * /airsim_ctrl/gain/track/Kvi0: 0.2
 * /airsim_ctrl/gain/track/Kvi1: 0.2
 * /airsim_ctrl/gain/track/Kvi2: 0.2
 * /airsim_ctrl/gain/track/Kyaw: 5.0
 * /airsim_ctrl/gra: 9.81
 * /airsim_ctrl/hov_percent: 0.593
 * /airsim_ctrl/hover/percent_higher_limit: 0.99
 * /airsim_ctrl/hover/percent_lower_limit: 0.4
 * /airsim_ctrl/hover/use_hov_percent_kf: False
 * /airsim_ctrl/mass: 0.8
 * /airsim_ctrl/msg_timeout/cmd: 0.5
 * /airsim_ctrl/msg_timeout/imu: 0.5
 * /airsim_ctrl/msg_timeout/odom: 0.5
 * /airsim_ctrl/msg_timeout/rc: 0.5
 * /airsim_ctrl/perform_aerodynamics_compensation: False
 * /airsim_ctrl/pxy_error_max: 0.6
 * /airsim_ctrl/pz_error_max: 0.3
 * /airsim_ctrl/use_yaw_rate_ctrl: False
 * /airsim_ctrl/vxy_error_max: 1.0
 * /airsim_ctrl/vz_error_max: 1.0
 * /airsim_ctrl/yaw_error_max: 0.7
 * /airsim_node/host_ip: localhost
 * /airsim_node/is_vulkan: False
 * /airsim_node/odom_frame_id: odom_local_enu
 * /airsim_node/publish_clock: False
 * /airsim_node/update_airsim_control_every_n_sec: 0.01
 * /airsim_node/update_airsim_img_response_every_n_sec: 0.03333333333333333
 * /airsim_node/update_lidar_every_n_sec: 0.01
 * /airsim_node/world_frame_id: world_enu
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    airsim_ctrl (airsim_ctrl/Ctrl_node)
    airsim_node (airsim_ros_pkgs/airsim_node)
    ned_to_enu_pub (tf/static_transform_publisher)
    world_pub (tf/static_transform_publisher)

WARNING: [/home/dell/APACE/src/APACE/airsim_ctrl/launch/ctrl_md_exploration.launch] unknown <arg> attribute 'type'
ROS_MASTER_URI=http://localhost:11311

process[airsim_node-1]: started with pid [1829541]
WARNING: Package name "TD3" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[ned_to_enu_pub-2]: started with pid [1829542]
process[world_pub-3]: started with pid [1829543]
process[airsim_ctrl-4]: started with pid [1829548]
[ INFO] [1719295525.540862826]: Initial value for hov_thr set to 0.59/0.59
[ INFO] [1719295525.541403919]: Hovering thrust kalman filter is NOT used.
Waiting for connection - 
Connected!

Client Ver:1 (Min Req:1), Server Ver:1 (Min Req:1)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unknown SimMode: , failed to set default vehicle settings
[airsim_node-1] process has died [pid 1829541, exit code -6, cmd /home/dell/APACE/devel/lib/airsim_ros_pkgs/airsim_node __name:=airsim_node __log:=/home/dell/.ros/log/52e60206-3246-11ef-94d3-1515a4912863/airsim_node-1.log].
log file: /home/dell/.ros/log/52e60206-3246-11ef-94d3-1515a4912863/airsim_node-1*.log

。我应该如何解决这个错误？

**Comment by xchencq** [comment]
Hi Andre, thank you for your interest!

I noticed an error message "failed to set default vehicle settings". And the error may due to a settings file missing.

I've just updated the repo with a _settings.json_ file. Please move this _settings.json_ file from the repository to _~/Documents/AirSim_ folder and replace the original one if any.

Thank you again and feel free for any other questions.
